## General disallowed methods
##
## When adding a disallowed method, a reason must be added. The reason
## can be a link to another rule that explains the reasoning behind the
## decision.
disallowed-methods = [
    # see lint map_unwrap_or
    "core::option::Option::map_or",
    # see lint map_unwrap_or
    "core::option::Option::map_or_else",
]
